#!/usr/bin/env bash

COMMAND=$@
$COMMAND
RESULT=$?

JOB=${PWD##*/}
DATE=$(date --iso-8601=seconds)
BRANCH=$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/')

if [ $RESULT -eq 0 ]; then
    MESSAGE="completed"
else
    MESSAGE="failed"
fi

DESCRIPTION="$JOB$BRANCH $MESSAGE on $DATE"

curl \
	-F apikey=$PROWL_API_TOKEN \
	-F application="PM projekt" \
	-F event="Build finished" \
	-F description="$DESCRIPTION" \
	https://api.prowlapp.com/publicapi/add
