#!/usr/bin/env Rscript

options(
  repos = c(CRAN = "https://cloud.r-project.org/"),
  install.packages.check.source = "no",
  install.packages.compile.from.source = "never"
)

packages_cran <- c(
  "AER",
  "arrow",
  "binb",
  "bookdown",
  "broom",
  "caret",
  "clipr",
  "cowplot",
  "data.table",
  "datapasta",
  "devtools",
  "dichromat",
  "diffobj",
  "dotenv",
  "estimatr",
  "eurostat",
  "fastDummies",
  "fst",
  "future",
  "future.apply",
  "gghighlight",
  "ggrepel",
  "ggridges",
  "grf",
  "gridExtra",
  "gsynth",
  "here",
  "hrbrthemes",
  "huxtable",
  "huxtable",
  "janitor",
  "lfe",
  "lintr",
  "lmtest",
  "margins",
  "microbenchmark",
  "minidown",
  "optparse",
  "patchwork",
  "plm",
  "prettydoc",
  "pwr",
  "randomizr",
  "roxygen2",
  "sandwich",
  "sjlabelled",
  "sjmisc",
  "skimr",
  "socviz",
  "stargazer",
  "sufrep",
  "svglite",
  "tesseract",
  "texreg",
  "tidyverse",
  "xtable",
  "zoo"
)

packages_github <- c(
  "svraka/asmisc",
  "svraka/aswp",
  "svraka/statoszt",
  "svraka/teroszt"
)

packages_gitlab <- c(
  "svraka/pmthemes"
)

install.packages(packages_cran)
remotes::install_github(packages_github)
remotes::install_gitlab(packages_gitlab)

if (.Platform$OS.type == "windows") {
  options(repos = c(getOption("repos"), Omegahat = "http://www.omegahat.net/R"))

  install.packages("RDCOMClient")
}
