#!/usr/bin/env Rscript

options(
  repos = c(CRAN = "https://cloud.r-project.org/"),
  install.packages.check.source = "no",
  install.packages.compile.from.source = "never"
)

packages_cran <- c(
  "tidyverse", "fst", # .Rprofile-ban!
  "eurostat", # adatforrasok
  "sjlabelled", #idegen formatumok beolvasasahoz
  "gsynth", "broom", "estimatr", "sandwich", "lmtest", "AER", "lfe", "plm", "huxtable", "margins", # okonometria
  "microbenchmark", "devtools", "roxygen2", "lintr", # fejlesztes
  "sjmisc", "skimr", "tesseract", "datapasta", "clipr", "janitor", "here", # hasznos
  "cowplot", "patchwork", "gridExtra", # Laying out plots
  "data.table", "zoo",
  "future", "future.apply", # parallel computing
  "randomizr", "pwr", # RCT-design
  "bookdown", "binb", "hrbrthemes", "prettydoc", "minidown", # RMarkdown
  "dichromat", "socviz", "ggrepel", "gghighlight", "ggridges", "svglite" # Viz
  "fastDummies",
  "texreg", "xtable", "stargazer", "huxtable",
  "grf", "caret", "sufrep", # ML
  "dotenv", "optparse", "diffobj", # tools
  "arrow"
)

packages_github <- c(
  "svraka/asmisc",
  "svraka/aswp",
  "svraka/statoszt",
  "svraka/teroszt"
)

packages_gitlab <- c(
  "svraka/pmthemes"
)

install.packages(packages_cran)
remotes::install_github(packages_github)
remotes::install_gitlab(packages_gitlab)

if (.Platform$OS.type == "windows") {
  options(repos = c(getOption("repos"), Omegahat = "http://www.omegahat.net/R"))

  install.packages("RDCOMClient")
}
