#!/usr/bin/env bash

dryrun=.
case "$1" in
    ""   ) dryrun="";;
    "-n" ) dryrun="-n -v";;
    *    ) echo "Unknown option"; exit 1;;
esac

RSYNC_OPTS=(-rltD $dryrun --modify-window=1 --delete --filter="-p .DS_Store" --exclude "Thumbs.db" --exclude "~\$*")

FROM=/Volumes/svraka
WHERE_LOCAL=/Users/andras
SMB="smb://malna.local/malnamedia"
WHERE_NETWORK=/Volumes/malnamedia
SHOULD_UNMOUNT=0

if [[ ! -d $FROM ]]; then
	echo "Error: volume $FROM not found, exiting."
	exit 1
fi

rsync "${RSYNC_OPTS[@]}" $FROM/SvrakaA/pm $WHERE_LOCAL/Documents/
rsync "${RSYNC_OPTS[@]}" $FROM/SvrakaA/Code/ $WHERE_LOCAL/Code/pmcode/
rsync "${RSYNC_OPTS[@]}" $FROM/pm_anaf $WHERE_LOCAL/Documents/
rsync "${RSYNC_OPTS[@]}" $FROM/pm_anaf_sharepoint $WHERE_LOCAL/Documents/

rsync "${RSYNC_OPTS[@]}" \
      --exclude /pm --exclude /Code \
      $FROM/SvrakaA/ $WHERE_LOCAL/Stuff/wkd11920/

echo -e "\n\033[0;32mNetwork backup\033[0m\n"

if [[ ! -d $WHERE_NETWORK ]]; then
	echo "Mounting \"$SMB\""
	osascript -e "mount volume \"$SMB\""
	SHOULD_UNMOUNT=1
fi

rsync "${RSYNC_OPTS[@]}" --progress $FROM/data $WHERE_NETWORK/
rsync "${RSYNC_OPTS[@]}" --progress $FROM/datatemp $WHERE_NETWORK/

if [[ $SHOULD_UNMOUNT == 1 ]]; then
	echo "Unmounting \"$WHERE_NETWORK\""
	umount "$WHERE_NETWORK"
fi
