#!/usr/bin/env Rscript

options(
  repos = c(CRAN = "https://cloud.r-project.org/"),
  install.packages.check.source = "no",
  install.packages.compile.from.source = "never"
)

if (.Platform$OS.type == "windows") {
  options(repos = c(getOption("repos"), Omegahat = "http://www.omegahat.net/R"))
}

update.packages()
