#!/usr/bin/env Rscript

# Set CRAN repo to automatic redirection. Using `getOption()` keeps
# any Rstudio Package Manager Setup from the site Rprofile.
local({
  r <- getOption("repos")
  r["CRAN"] <- "https://cloud.r-project.org/"
  options(repos = r)
})

options(
  install.packages.check.source = "no",
  install.packages.compile.from.source = "never"
)

if (.Platform$OS.type == "windows") {
  options(repos = c(getOption("repos"), Omegahat = "http://www.omegahat.net/R"))
}

update.packages()
